// QUERY METHODS
export const QUERY_AUTHOR = 'QUERY_AUTHOR';
export const QUERY_LABELS = 'QUERY_LABELS';
export const QUERY_STATE = 'QUERY_STATE';
export const QUERY_ASSIGNEE = 'QUERY_ASSIGNEE';
export const QUERY_MENTIONED = 'QUERY_MENTIONED';
export const QUERY_MILESTONE = 'QUERY_MILESTONE';
export const QUERY_SORT = 'QUERY_SORT';
export const QUERY_DIRECTION = 'QUERY_DIRECTION';
export const QUERY_SINCE = 'QUERY_SINCE';

// QUERY RESULT
export const QUERY_REQUEST = 'QUERY_REQUEST'
export const QUERY_ERROR = 'QUERY_ERROR'
export const QUERY_SUCCESS = 'QUERY_SUCCESS'; 
export const INITIAL_QUERY_SUCCESS = 'INITIAL_QUERY_SUCCESS'